# Generated by Django 4.2.20 on 2025-05-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
